site_name: benny
site_url: https://www.playbenny.com/
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: amber
  logo: benny_logo_800.png
  features: 
    - navigation.footer
repo: https://github.com/jamesholdenmusic/benny    
nav:
  - Home: index.md
  - Article: article.md