site_name: benny
site_url: https://www.playbenny.com/
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: amber
  logo: assets/benny_logo_400T.png
  favicon: assets/favicon-32x32.png
  features: 
    - navigation.footer
    - header.autohide
  markdown_extensions:
    - attr_list
extra:
  generator: false
repo: https://github.com/jamesholdenmusic/benny    
nav:
  - Home: index.md
  - About: about.md
  - Blocks : blocks.md
  - Sidebar : sidebar.md
  - Connections : connections.md
  - States : states.md
  - Waves : waves.md
  - Panels : panels.md
  - Installation: installation.md
  - Midi Control: controllers.md
  - Recording: recording.md
  - Playing live sets with benny: live_sets.md
  - Keyboard shortcuts: keyboard_shortcuts.md
  - Developing blocks: developing.md